config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        confirmations: 'users/confirmations'
      }
  # Pages routes
  get 'pages/about_us', to: 'pages#about_us', as: :about_us
  get 'pages/contact_us', to: 'pages#contact_us', as: :contact_us
  get 'pages/privacy_policy', to: 'pages#privacy_policy', as: :privacy_policy
  get 'pages/terms_and_conditions', to: 'pages#terms_and_conditions', as: :terms_and_conditions

  # Home routes
  root 'home#index'
  # You can remove the following lines as they are not necessary.
  # get 'home/index', as: :home_index
  # get 'home/edit', as: :home_edit
  # get 'home/show', as: :home_show

  # Employee and Document resources
  resources :employees
  resources :documents
end

app/models/employee.rb
class Employee < ApplicationRecord
	has_many :documents
	validates :first_name, :last_name, presence: true
	validates :personal_email, presence: true, uniqueness: true
	validates :city, :state, :country, :pincode, :address_line_1, presence: true
	def name
		"#{first_name} #{last_name}".strip
	end
	def full_address
		"#{address_line_1} #{city}, #{state}, #{country}, #{pincode}".strip
	end
	def name_with_email
		"#{name}(#{personal_email})"
	end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:edit, :update, :show, :destroy]
  def index
    @employees = Employee.all
  end
  def new
    @employee = Employee.new
  end
  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to employee_path(@employee), notice: 'Employee has been created sucessfully'
    else
      render :new
    end
  end
  def edit
  end
  def update
    if @employee.update(employee_params)
      redirect_to employee_path, notice: "Employee has been updated sucessfully"
    else
      render :edit
    end
  end
  def show
  end
  def destroy
    if @employee.destroy
      redirect_to employees_path, notice: 'Employee has been deleted sucessfully'
    else
      redirect_to employee_path(@employee), alert: 'Failed to delete employee'
    end
  end
  private
  def employee_params
    params.require(:employee).permit(:first_name, :middle_name, :last_name, :personal_email, :city, :state, :country, :pincode, :address_line_1, :address_line_2)
  end
  def set_employee
    @employee = Employee.find(params[:id])
  rescue ActiveRecord::RecordNotFound => error
    redirect_to employee_path, notice: error
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with model: employee do |form| %>
    <div class="row">
    	<div class="col-lg-4">
    	  <div class="form-group">
    		<%= form.label :first_name, class: 'mb-2' %>
    		<%= form.text_field :first_name, class: 'form-control form-control-lg rounded-0' %>
    		<% @employee.errors.full_messages_for(:first_name).each do |message| %>
    	 	<p class="text-danger"><%= message %></p>
    	 	<% end %>
    	  </div>
    	</div>
    	<div class="col-lg-4">
    	 <div class="form-group">
    		<%= form.label :middle_name, class: 'mb-2' %>
    		<%= form.text_field :middle_name, class: 'form-control form-control-lg rounded-0' %>
    	 </div>
    	</div>
    	<div class="col-lg-4">
    	  <div class="form-group">
    		<%= form.label :last_name, class: 'mb-2' %>
    		<%= form.text_field :last_name, class: 'form-control form-control-lg rounded-0' %>
    		<% @employee.errors.full_messages_for(:last_name).each do |message| %>
    	 	<p class="text-danger"><%= message %></p>
    	 	<% end %>
    	  </div>
    	</div>  
    </div>
    <div class="row">
      <div class="col-lg-4">
    	<div class="form-group">
    		<%= form.label :personal_email, class: 'mb-2' %>
    		<%= form.email_field :personal_email, class: 'form-control form-control-lg rounded-0' %>
    		<% @employee.errors.full_messages_for(:personal_email).each do |message| %>
    	 	<p class="text-danger"><%= message %></p>
    	 	<% end %>
    	</div>	
      </div>
    </div>
     <div class="row">
      <div class="col-lg-6">
    	<div class="form-group">
    		<%= form.label :address_line_1, class: 'mb-2' %>
    		<%= form.text_field :address_line_1, class: 'form-control form-control-lg rounded-0' %>
    		<% @employee.errors.full_messages_for(:address_line_1).each do |message| %>
    	 	<p class="text-danger"><%= message %></p>
    	 	<% end %>
    	</div>	
      </div>
      <div class="col-lg-6">
    	<div class="form-group">
    		<%= form.label :address_line_2, class: 'mb-2' %>
    		<%= form.text_field :address_line_2, class: 'form-control form-control-lg rounded-0' %>
    	</div>	
      </div>
      <div class="col-lg-3">
    	<div class="form-group">
    		<%= form.label :city, class: 'mb-2' %>
    		<%= form.text_field :city, class: 'form-control form-control-lg rounded-0' %>
    		<% @employee.errors.full_messages_for(:city).each do |message| %>
    	 	<p class="text-danger"><%= message %></p>
    	 	<% end %>
    	</div>	
      </div>
      <div class="col-lg-3">
    	<div class="form-group">
    		<%= form.label :state, class: 'mb-2' %>
    		<%= form.text_field :state, class: 'form-control form-control-lg rounded-0' %>
    		<% @employee.errors.full_messages_for(:state).each do |message| %>
    	 	<p class="text-danger"><%= message %></p>
    	 	<% end %>
    	</div>	
      </div>
      <div class="col-lg-3">
    	<div class="form-group">
    		<%= form.label :country, class: 'mb-2' %>
    		<%= form.text_field :country, class: 'form-control form-control-lg rounded-0' %>
    		<% @employee.errors.full_messages_for(:country).each do |message| %>
    	 	<p class="text-danger"><%= message %></p>
    	 	<% end %>
    	</div>	
      </div>
      <div class="col-lg-3">
    	<div class="form-group">
    		<%= form.label :pincode, class: 'mb-2' %>
    		<%= form.text_field :pincode, class: 'form-control form-control-lg rounded-0' %>
    		<% @employee.errors.full_messages_for(:pincode).each do |message| %>
    	 	<p class="text-danger"><%= message %></p>
    	 	<% end %>
    	</div>	
      </div>
    </div>
    <div class="row">
    	<div class="col-lg-12 mt-4">
    		<%= form.submit class: 'btn btn-primary btn-lg rounded-0' %>
    		<%= link_to "Back to Employess", employees_path, class: "btn btn-outline-primary btn-lg rounded-0" %>
    	</div>
    </div>
  <% end %>

app/views/employees/edit.html.erb
<div class="col-lg-12">
 <div class="card rounded-0 mt-5 mb-5">
	<div class="card_body">
		<h2 class="text-center">Edit Employee Information</h2>
	</div>
 </div>
  <%= render 'form', employee: @employee %>
</div>

app/views/employees/index.html.erb
<div class="col-lg-12">
	<%= flash[:notice]  %>
 <div class="card rounded-0 mt-5 mb-5">
	<div class="card_body">
		<h2 class="text-center">Listing Emlpoyees</h2>
	</div>
 </div>
 <%= link_to "Create New Emlpoyee", new_employee_path, class: "btn btn-primary btn-lg mb-4 rounded-0"  %>
 <%= link_to "Add Document", new_document_path, class: "btn btn-success btn-lg mb-4 rounded-0" %>
 <table class="table table-bordered">
	<thead>
	  <tr>
		<th>Name</th>
		<th>Email</th>
		<th>Address</th>
		<th>Actions</th>
	  </tr>
	</thead>
	<tbody>
		<% @employees.each do |employee| %>
		<tr>
			<td><%= employee.name %></td>
			<td><%= employee.personal_email %></td>
			<td><%= employee.full_address %></td>
			<td><%= link_to "Edit", edit_employee_path(employee), class: "btn btn-primary" %></td>
			<td><%= link_to "View", employee_path(employee), class: "btn btn-info" %></td>
			<td><%= link_to "Delete", employee_path(employee), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure to delete this employee?' } %></td>
		</tr>
		<% end %>
	</tbody>
 </table>
</div>

app/views/employees/new.html.erb
<div class="col-lg-12">
 <div class="card rounded-0 mt-5 mb-5">
	<div class="card_body">
		<h2 class="text-center">Create New Employee</h2>
	</div>
 </div>
 <%= render 'form', employee: @employee %>
</div>

app/views/employees/show.html.erb
<div class="col-lg-12">
 <div class="card rounded-0 mt-5 mb-5">
	<div class="card-body">
		<h2 class="text-center">Employee Details</h2>
		<div class="row mt-5">
			<div class="col-lg-6">
				<h3 class="text-center mb-3">Personal Information</h3>
				<p class="lead"><strong>First Name:</strong><%= @employee.first_name %></p>
				<p class="lead"><strong>Middle Name:</strong><%= @employee.middle_name.present? ? @employee.middle_name : '--NA--' %></p>
				<p class="lead"><strong>Last Name:</strong><%= @employee.last_name %></p>
				<p class="lead"><strong>Personal Email:</strong><%= @employee.personal_email %></p>
			</div>
			<div class="col-lg-6">
				<h3 class="text-center mb-3">Address Information</h3>
				<p class="lead"><strong>Address Line 1:</strong><%= @employee.address_line_1 %></p>
				<p class="lead"><strong>Address Line 2:</strong><%= @employee.address_line_2.present? ? @employee.address_line_2 : '--NA--' %></p>
				<p class="lead"><strong>City:</strong><%= @employee.city %></p>
				<p class="lead"><strong>State:</strong><%= @employee.state %></p>
				<p class="lead"><strong>Country:</strong><%= @employee.country %></p>
				<p class="lead"><strong>Pincode:</strong><%= @employee.pincode %></p>
			</div>
		 </div>
		 <% if @employee.documents.present? %>
		 <div class="row mt-5">
			<h2 class="text-center">Employee Documents</h2>
			<% @employee.documents.each do |document| %>
			<div class="card mb-4">
				<div class="card-body">
					<div class="row">
						<% if document.image.attached? %>
						<div class="col-lg-4">
							<%= image_tag document.image, class: 'img-fluid'  %>
						</div>
						<% end %>
						<div class="col-lg-4">
							<p class="lead"><%= document.name %></p>
						</div>
						<div class="col-lg-4">
							<p><%= document.doc_type %></p>
						</div>
					</div>
				</div>
			</div>
		 <% end %>
		 </div>
		<% end %>
		<%= link_to 'Back to Employess', employees_path, class: 'btn btn-outline-primary btn-lg rounded-0' %>
	    <%= link_to 'Edit Employes', edit_employee_path(@employee), class: 'btn btn-primary btn-lg rounded-0' %>
	</div>
 </div>
</div>