config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        confirmations: 'users/confirmations'
      }
  # Pages routes
  get 'pages/about_us', to: 'pages#about_us', as: :about_us
  get 'pages/contact_us', to: 'pages#contact_us', as: :contact_us
  get 'pages/privacy_policy', to: 'pages#privacy_policy', as: :privacy_policy
  get 'pages/terms_and_conditions', to: 'pages#terms_and_conditions', as: :terms_and_conditions

  # Home routes
  root 'home#index'
  # You can remove the following lines as they are not necessary.
  # get 'home/index', as: :home_index
  # get 'home/edit', as: :home_edit
  # get 'home/show', as: :home_show

  # Employee and Document resources
  resources :employees
  resources :documents
end

app/views/shared/_dummy_content.html.erb
<p class="lead">
	There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc.
</p>

app/views/shared/_footer.html.erb
<h1>HR-Mitra</h1>
<%= link_to 'About Us', about_us_path, target: '_blank', style: 'color:red;' %>
<%= link_to 'Contact Us', contact_us_path, target: '_blank', style: 'color:red;' %>
<%= link_to 'Privacy Policy', privacy_policy_path, target: '_blank', style: 'color:red;' %>
<%= link_to 'Terms And Conditions', terms_and_conditions_path, target: '_blank', style: 'color:red;' %>

app/views/shared/_header.html.erb
<style>
  /* Navbar styles */
  .navbar {
    background-color: #007BFF; /* Blue background color */
    color: #fff;
  }

  .navbar-brand {
    color: #fff;
    font-weight: bold;
    font-size: 24px;
  }

  .navbar-toggler {
    border: none;
    color: #fff;
  }

  .navbar-toggler-icon {
    background-image: url('data:image/svg+xml;charset=utf8,%3Csvg viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg" class="iconify" fill="%23fff"%3E%3Cpath d="M4 8v2h24V8zm0 6v2h24v-2zm0 6v2h24v-2z"%3E%3C/path%3E%3C/svg%3E');
  }

  .navbar-nav .nav-link {
    color: #fff;
    font-size: 18px;
    margin-left: 10px;
  }

  .navbar-nav .nav-link:hover {
    color: #f00; /* Change the color on hover as desired */
  }

  .dropdown-menu {
    background-color: #007BFF; /* Blue background color for dropdown */
    border: none;
  }

  .dropdown-item {
    color: #fff;
    font-size: 16px;
  }

  .dropdown-item:hover {
    background-color: #f00; /* Change the background color on hover as desired */
  }

  .dropdown-divider {
    border-top: 1px solid #fff;
  }
   .navbar .dropdown-menu {
    right: 0;
    left: auto;
  }
</style>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to 'HR-Mitra', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About Us', about_us_path, target: '_blank', class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contact Us', contact_us_path, target: '_blank', class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Privacy Policy', privacy_policy_path, target: '_blank', class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Terms and Conditions', terms_and_conditions_path, target: '_blank', class: 'nav-link' %>
        </li>
      </ul>
      <% if user_signed_in? %>
        <ul class="navbar-nav"> <!-- Move this line inside the 'collapse' div -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Settings
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <%= link_to "Logged in as #{current_user.email}", "javascript:void(0)", class: 'dropdown-item', disabled: true %>
              </li>
              <li>
                <%= link_to 'Sign Out', destroy_user_session_path, class: 'dropdown-item', method: :delete, data: { confirm: 'Are you sure you want to Logout?' } %>
              </li>
            </ul>
          </li>
        </ul>
      <% else %>
        <a href="<%= new_user_session_path %>" class="btn btn-light mx-2">Sign In</a>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_links.html.erb
<style>
  .footer {
    background-color: #007BFF; /* Blue background color */
    padding: 30px 0;
  }
  .footer h4 {
    color: #fff;
    margin-bottom: 20px;
  }
  .footer p,
  .footer a {
    color: #fff;
  }
  .footer a:hover {
    text-decoration: none;
    color: #f00; /* Change the color on hover as desired */
  }
</style>

<footer class="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h4>About Us</h4>
        <p>We are a company that provides HR solutions to businesses of all sizes.</p>
      </div>
      <div class="col-md-4">
        <h4>Pages</h4>
        <ul class="list-unstyled">
          <li><%= link_to 'About Us', about_us_path, target: '_blank', class: 'text-white' %></li>
          <li><%= link_to 'Contact Us', contact_us_path, target: '_blank', class: 'text-white' %></li>
          <li><%= link_to 'Privacy Policy', privacy_policy_path, target: '_blank', class: 'text-white' %></li>
          <li><%= link_to 'Terms and Conditions', terms_and_conditions_path, target: '_blank', class: 'text-white' %></li>
        </ul>
      </div>
      <div class="col-md-4">
        <h4>Contact Us</h4>
        <p>Email: <a href="mailto:info@example.com" class="text-white">info@example.com</a></p>
        <p>Phone: (123) 456-7890</p>
      </div>
    </div>
  </div>
</footer>