config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations',
        passwords: 'users/passwords',
        confirmations: 'users/confirmations'
      }
  # Pages routes
  get 'pages/about_us', to: 'pages#about_us', as: :about_us
  get 'pages/contact_us', to: 'pages#contact_us', as: :contact_us
  get 'pages/privacy_policy', to: 'pages#privacy_policy', as: :privacy_policy
  get 'pages/terms_and_conditions', to: 'pages#terms_and_conditions', as: :terms_and_conditions

  # Home routes
  root 'home#index'
  # You can remove the following lines as they are not necessary.
  # get 'home/index', as: :home_index
  # get 'home/edit', as: :home_edit
  # get 'home/show', as: :home_show

  # Employee and Document resources
  resources :employees
  resources :documents
end

app/models/document.rb
class Document < ApplicationRecord
  DOC_TYPES = ['Personal ID','Marksheet', 'Photo Id', 'Address Proof' ,'Others'].freeze
  belongs_to :employee
  has_one_attached :image
  validates :name, :doc_type, presence: true
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
	before_action :set_document, only: [:edit, :update, :show, :destroy]
  def index
    @documents = Document.all
  end
  def new
    @document = Document.new
  end
  def create
    @document = Document.new(document_params)
    if @document.save
      redirect_to document_path(@document), notice: 'Document has been created sucessfully'
    else
      render :new
    end
  end
  def edit
  end
  def update
    if @document.update(document_params)
      redirect_to document_path, notice: "Document has been updated sucessfully"
    else
      render :edit
    end
  end
  def show
  end
  def destroy
    if @document.destroy
      redirect_to documents_path, notice: 'Document has been deleted sucessfully'
    else
      redirect_to document_path(@document), alert: 'Failed to delete document'
    end
  end
  private
  def document_params
    params.require(:document).permit(:name, :doc_type, :employee_id, :image )
  end
  def set_document
    @document = Document.find(params[:id])
  rescue ActiveRecord::RecordNotFound => error
    redirect_to document_path, notice: error
  end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_with model: document do |form| %>
  <div class="row">
  	<div class="col-lg-4">
  		<div class="form-group">
  			<%= form.label :name, class: 'mb-2' %>
    		<%= form.text_field :name, class: 'form-control form-control-lg rounded-0' %>
    		<% @document.errors.full_messages_for(:name).each do |message| %>
    	 	<p class="text-danger"><%= message %></p>
    	 	<% end %>
  		</div>
  		<div class="form-group">
  			<%= form.label :doc_type, class: 'mb-2' %>
        <%= form.select :doc_type,options_for_select(Document::DOC_TYPES, selected: document.doc_type),{prompt: 'Select Document Type'}, { class: 'form-select form-select-lg rounded-0' } %>
    		<% @document.errors.full_messages_for(:doc_type).each do |message| %>
    	 	<p class="text-danger"><%= message %></p>
    	 	<% end %>
  		</div>
  		<div class="form-group">
  			<%= form.label :employee_id, class: 'mb-2' %>
    		<%= form.select :employee_id,options_for_select(Employee.all.map {|employee| [employee.name_with_email,employee.id]} , selected: document.employee_id),{prompt: 'Select Employee'}, { class: 'form-select form-select-lg rounded-0' } %>
    		<% @document.errors.full_messages_for(:employee_id).each do |message| %>
    	 	<p class="text-danger"><%= message %></p>
    	 	<% end %>
  		</div>
      <div class="form-group">
        <%= form.label :image, class: 'mb-2' %><br>
        <%= form.file_field :image %>
      </div>
  	</div>
    <div class="row">
      <div class="col-lg-12 mt-4">
        <%= form.submit class: 'btn btn-primary btn-lg rounded-0' %>
        <%= link_to "Back to Documents", documents_path, class: "btn btn-outline-primary btn-lg rounded-0" %>
      </div>
    </div>
  </div>
  <% end %>

app/views/documents/edit.html.erb
<div class="col-lg-12">
 <div class="card rounded-0 mt-5 mb-5">
	<div class="card_body">
		<h2 class="text-center">Edit Document</h2>
	</div>
 </div>
 <%= render 'form', document: @document %>
</div>

app/views/documents/index.html.erb
<div class="col-lg-12">
	<%= flash[:notice]  %>
 <div class="card rounded-0 mt-5 mb-5">
	<div class="card_body">
		<h2 class="text-center">Listing Emlpoyees Documents</h2>
	</div>
 </div>
 <%= link_to "Create New Document", new_document_path, class: "btn btn-primary btn-lg mb-4 rounded-0"  %>
 <%= link_to "Back to Employees", employees_path, class: "btn btn-primary btn-lg mb-4 rounded-0" %>
 <table class="table table-bordered">
	<thead>
	  <tr>
		<th>Name</th>
		<th>Doc Type</th>
		<th>Employee</th>
		<th>Actions</th>
	  </tr>
	</thead>
	<tbody>
		<% @documents.each do |document| %>
		<tr>
			<td><%= document.name %></td>
			<td><%= document.doc_type %></td>
			<td><%= link_to document.employee.name, employee_path(document.employee) %></td>
			<td><%= link_to "Edit", edit_document_path(document), class: "btn btn-primary" %></td>
			<td><%= link_to "View", document_path(document), class: "btn btn-info" %></td>
			<td><%= link_to "Delete", document_path(document), class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure to delete this document?' } %></td>
		</tr>
		<% end %>
	</tbody>
 </table>
</div>

app/views/documents/new.html.erb
<div class="col-lg-12">
 <div class="card rounded-0 mt-5 mb-5">
	<div class="card_body">
		<h2 class="text-center">Create New Document</h2>
	</div>
 </div>
 <%= render 'form', document: @document %>
</div>

app/views/documents/show.html.erb
<div class="col-lg-12">
 <div class="card rounded-0 mt-5 mb-5">
	<div class="card_body">
		<h2 class="text-center">Doc Details</h2>
		<div class="row mt-5">
			<div class="col-lg-6">
				<% if @document.image.attached? %>
				<%= image_tag @document.image, class: 'img-fluid'  %>
				<% end %>
				<p class="lead"><strong>Name:</strong><%= @document.name %></p>
				<p class="lead"><strong>Type:</strong><%= @document.doc_type %></p>
				<p class="lead"><strong>Employee:</strong><%= @document.employee.name %></p>
			</div>
		</div>
		<%= link_to 'Back to Documents', documents_path, class: 'btn btn-outline-primary btn-lg rounded-0' %>
	    <%= link_to 'Edit Documents', edit_document_path(@document), class: 'btn btn-primary btn-lg rounded-0' %>
	</div>
 </div>
</div>